version: "3.1"

services:
  web:
    image: webdevops/php-apache-dev:8.0
    ports:
      - "8008:8023"
    volumes:
      - ./public:/public
    environment:
      WEB_DOCUMENT_ROOT: /public
      WEB_DOCUMENT_INDEX: index.php

  
  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./database/database.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
    - 8081:3306
    environment:
      MYSQL_USER: admin
      MYSQL_DATABASE: delivery_sys_laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini